name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install rust toolchain
      run: rustup toolchain install 1.61.0
    - name: Set default rust toolchain
      run: rustup default 1.61.0
    - name: Install wasm-pack
      run: cargo install --version 0.10.2 wasm-pack
    - name: Install node_modules
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
