name: Build

on: push

# Stops the running workflow of previous pushes
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_VERSION: stable
  NODE_VERSION: 12
  WASM_PACK_VERSION: 0.10.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        registry-url: https://registry.npmjs.org/

    - name: Set default Rust version - ${{ env.RUST_VERSION }}
      run: rustup default ${{ env.RUST_VERSION }}

    - name: Install wasm-pack
      run: cargo install --version ${{ env.WASM_PACK_VERSION }} wasm-pack

    - name: Install node_modules
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test
