name: Publish

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 12
        cache: 'npm'
        registry-url: https://registry.npmjs.org/
    - name: Install rust toolchain
      run: rustup toolchain install 1.61.0
    - name: Set default rust toolchain
      run: rustup default 1.61.0
    - name: Install wasm-pack
      run: cargo install --version 0.10.2 wasm-pack
    - name: Build
      run: npm run build
    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
